### ISSUE TITLE
Checkov Pipeline Improvement 

### ISSUE THREAD

**Issue by madhurshukla23jan** [AErmie/DevSecOps#52]
**Describe the bug**
Hello @AErmie,

for https://github.com/AErmie/DevSecOps/blob/main/azure-pipelines/terraform-checkov-pipeline.yml
If you remove "terraform" from the script, it will start publishing artifacts to ADO Test Results with proper output. 
docker run -v $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov --directory /tf --output junitxml > $(System.DefaultWorkingDirectory)/CheckovReport/Checkov-Report.xml
docker run -v $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov --directory /tf
![image](https://user-images.githubusercontent.com/5002916/210490067-f9106ad6-2b10-4503-bfc2-6a4474159e71.png)

**Additional context**
However now there is different problem. The pipeline will exit with code "1"
![image](https://user-images.githubusercontent.com/5002916/210489818-3ca304c7-6cf3-4c39-a886-943b8905f9d7.png)

I was able to solve that by adding the scripts in Bash file and not running as inline commands. Like below:
    - job: CheckovSecurityRecommendationCI
      displayName: Checkov Security Recommendation CI - Job
      pool:
        vmImage: ubuntu-20.04
      steps:
      # Step 1: Run the Checkov Static Code Analysis
      - bash: $(terraformWorkingDirectory)/checkov.sh $(terraformWorkingDirectory)
        displayName: Security and Compliance Check - Checkov

**Comment by AErmie** [comment]
Thanks @madhurshukla23jan, I've made the change in the pipeline file. Sorry for the delay, I was busy re-structuring my repo to make it easier to work with different tools, targets, etc.

FYI, the pipeline is expected to exit with a non-zero code if there are any vulnerabilities found by Checkov. You can control that through the [Checkov CLI](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html)., in particular the `--soft-fail` command, and/or `--soft-fail-on`, `--hard-fail-on` commands (ie. if you only want to fail on CRITICAL vulnerabilities).
